import express from 'express'
import cors from 'cors'
import { DatabaseSync } from 'node:sqlite'
import crypto from 'node:crypto'

const app=express(), db=new DatabaseSync('business.db'), secret=process.env.APP_SECRET||'vyapaar-flow-demo-secret'
db.exec('PRAGMA foreign_keys=ON')
app.use(cors());app.use(express.json())
db.exec(`CREATE TABLE IF NOT EXISTS business(id INTEGER PRIMARY KEY,name TEXT,owner TEXT,phone TEXT,gstin TEXT,address TEXT);CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT,email TEXT UNIQUE,password_hash TEXT,role TEXT);CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,name TEXT NOT NULL,sku TEXT UNIQUE,category TEXT,unit TEXT DEFAULT 'piece',cost REAL DEFAULT 0,price REAL NOT NULL,stock INTEGER DEFAULT 0,reorder_level INTEGER DEFAULT 5,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY,name TEXT NOT NULL,phone TEXT,address TEXT,tag TEXT DEFAULT 'Regular',balance REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY,customer_id INTEGER,total REAL NOT NULL,payment_mode TEXT NOT NULL,paid REAL NOT NULL,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS sale_items(id INTEGER PRIMARY KEY,sale_id INTEGER NOT NULL,product_id INTEGER NOT NULL,quantity INTEGER NOT NULL,unit_price REAL NOT NULL);CREATE TABLE IF NOT EXISTS stock_movements(id INTEGER PRIMARY KEY,product_id INTEGER NOT NULL,quantity INTEGER NOT NULL,reason TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`)
try{db.exec('ALTER TABLE sales ADD COLUMN created_by INTEGER')}catch{}
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'), rows=(s,a=[])=>db.prepare(s).all(...a)
const tx=work=>{db.exec('BEGIN');try{const r=work();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}
const token=u=>{const p=Buffer.from(JSON.stringify({id:u.id,name:u.name,role:u.role,expires:Date.now()+86400000})).toString('base64url'),s=crypto.createHmac('sha256',secret).update(`${u.id}${u.role}`).digest('base64url');return `${p}.${s}`}
const auth=(req,res,next)=>{try{const [p,s]=(req.headers.authorization||'').replace('Bearer ','').split('.'),u=JSON.parse(Buffer.from(p,'base64url'));if(s!==crypto.createHmac('sha256',secret).update(`${u.id}${u.role}`).digest('base64url')||u.expires<Date.now())throw 0;req.user=u;next()}catch{return res.status(401).json({error:'Please sign in again'})}}
const owner=(req,res,next)=>req.user.role==='owner'?next():res.status(403).json({error:'Owner access required'})
if(!db.prepare('SELECT id FROM business').get()){db.prepare('INSERT INTO business(name,owner,phone,gstin,address) VALUES(?,?,?,?,?)').run('Annapoorna Stores','Priya Nair','+91 98765 43210','33ABCDE1234F1Z5','12 Market Road, Chennai');const a=db.prepare('INSERT INTO products(name,sku,category,unit,cost,price,stock,reorder_level) VALUES(?,?,?,?,?,?,?,?)');[['Ponni Rice 5kg','RIC-005','Grains','bag',275,325,18,8],['Aashirvaad Atta 5kg','ATT-005','Flour','bag',240,285,6,8],['Tata Salt 1kg','SAL-001','Essentials','pack',19,25,32,12],['Fortune Sunflower Oil 1L','OIL-001','Oil','bottle',120,145,4,6],['Britannia Good Day','BIS-100','Snacks','pack',20,30,24,10]].forEach(x=>a.run(...x));const c=db.prepare('INSERT INTO customers(name,phone,address,tag,balance) VALUES(?,?,?,?,?)');[['Ravi Kumar','+91 98401 22334','T Nagar','Regular',350],['Meena Stores','+91 98840 99111','Mylapore','Wholesale',0],['Arjun S','+91 97910 55221','Adyar','Regular',125]].forEach(x=>c.run(...x))}
if(!db.prepare('SELECT id FROM users').get()){const a=db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)');a.run('Priya Nair','owner@annapoorna.test',hash('owner123'),'owner');a.run('Karthik Kumar','cashier@annapoorna.test',hash('cashier123'),'cashier')}
app.post('/api/auth/login',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get(req.body.email?.toLowerCase());if(!u||u.password_hash!==hash(req.body.password||''))return res.status(401).json({error:'Incorrect email or password'});res.json({token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})})
app.get('/api/auth/me',auth,(req,res)=>res.json({user:req.user}))
app.get('/api/dashboard',auth,(_q,res)=>{const d=db.prepare("SELECT COALESCE(SUM(total),0)total,COUNT(*)orders FROM sales WHERE date(created_at)=date('now','localtime')").get();res.json({...d,products:db.prepare('SELECT COUNT(*)count FROM products').get().count,lowStock:rows('SELECT * FROM products WHERE stock<=reorder_level ORDER BY stock'),credit:db.prepare('SELECT COALESCE(SUM(balance),0)total FROM customers').get().total,recentSales:rows('SELECT s.*,c.name customer_name FROM sales s LEFT JOIN customers c ON c.id=s.customer_id ORDER BY s.created_at DESC LIMIT 6'),topProducts:rows('SELECT p.name,COALESCE(SUM(si.quantity),0)sold FROM products p LEFT JOIN sale_items si ON si.product_id=p.id GROUP BY p.id ORDER BY sold DESC LIMIT 5')})})
app.get('/api/business',auth,(_q,res)=>res.json(db.prepare('SELECT * FROM business LIMIT 1').get()))
app.put('/api/business',auth,owner,(req,res)=>{const b=req.body;db.prepare('UPDATE business SET name=?,owner=?,phone=?,gstin=?,address=? WHERE id=1').run(b.name,b.owner,b.phone,b.gstin,b.address);res.json({ok:true})})
app.get('/api/products',auth,(req,res)=>{const q=`%${req.query.q||''}%`;res.json(rows('SELECT * FROM products WHERE name LIKE ? OR sku LIKE ? OR category LIKE ? ORDER BY name',[q,q,q]))})
app.post('/api/products',auth,owner,(req,res)=>{const p=req.body,r=db.prepare('INSERT INTO products(name,sku,category,unit,cost,price,stock,reorder_level)VALUES(?,?,?,?,?,?,?,?)').run(p.name,p.sku||null,p.category,p.unit||'piece',+p.cost||0,+p.price,+p.stock||0,+p.reorder_level||5);if(+p.stock)db.prepare('INSERT INTO stock_movements(product_id,quantity,reason)VALUES(?,?,?)').run(r.lastInsertRowid,+p.stock,'Opening stock');res.json({id:r.lastInsertRowid})})
app.patch('/api/products/:id/stock',auth,owner,(req,res)=>{const d=+req.body.quantity,p=db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id);if(!p||p.stock+d<0)return res.status(400).json({error:'Insufficient stock'});tx(()=>{db.prepare('UPDATE products SET stock=stock+? WHERE id=?').run(d,p.id);db.prepare('INSERT INTO stock_movements(product_id,quantity,reason)VALUES(?,?,?)').run(p.id,d,req.body.reason||'Manual adjustment')});res.json({ok:true})})
app.get('/api/customers',auth,(req,res)=>{const q=`%${req.query.q||''}%`;res.json(rows('SELECT * FROM customers WHERE name LIKE ? OR phone LIKE ? OR tag LIKE ? ORDER BY name',[q,q,q]))})
app.post('/api/customers',auth,(req,res)=>{const c=req.body,r=db.prepare('INSERT INTO customers(name,phone,address,tag)VALUES(?,?,?,?)').run(c.name,c.phone||'',c.address||'',c.tag||'Regular');res.json({id:r.lastInsertRowid})})
app.get('/api/sales',auth,(_q,res)=>res.json(rows(`SELECT s.*,c.name customer_name,u.name staff_name,GROUP_CONCAT(p.name||' ×'||si.quantity,', ')items FROM sales s LEFT JOIN customers c ON c.id=s.customer_id LEFT JOIN users u ON u.id=s.created_by LEFT JOIN sale_items si ON si.sale_id=s.id LEFT JOIN products p ON p.id=si.product_id GROUP BY s.id ORDER BY s.created_at DESC`)))
app.get('/api/sales/:id',auth,(req,res)=>{const s=db.prepare('SELECT s.*,c.name customer_name,c.phone customer_phone,b.name business_name,b.address,b.phone business_phone,b.gstin FROM sales s LEFT JOIN customers c ON c.id=s.customer_id CROSS JOIN business b WHERE s.id=?').get(req.params.id);if(!s)return res.status(404).json({error:'Sale not found'});s.items=rows('SELECT si.*,p.name,p.sku,p.unit FROM sale_items si JOIN products p ON p.id=si.product_id WHERE si.sale_id=?',[s.id]);res.json(s)})
app.post('/api/sales',auth,(req,res)=>{const{customerId,paymentMode,paid,items}=req.body;if(!items?.length)return res.status(400).json({error:'Add at least one item'});try{res.json(tx(()=>{let total=0;for(const i of items){const p=db.prepare('SELECT * FROM products WHERE id=?').get(i.productId);if(!p||p.stock<i.quantity)throw Error(`Insufficient stock for ${p?.name||'product'}`);total+=p.price*i.quantity}const s=db.prepare('INSERT INTO sales(customer_id,total,payment_mode,paid,created_by)VALUES(?,?,?,?,?)').run(customerId||null,total,paymentMode||'Cash',+paid||0,req.user.id);for(const i of items){const p=db.prepare('SELECT * FROM products WHERE id=?').get(i.productId);db.prepare('INSERT INTO sale_items(sale_id,product_id,quantity,unit_price)VALUES(?,?,?,?)').run(s.lastInsertRowid,p.id,i.quantity,p.price);db.prepare('UPDATE products SET stock=stock-? WHERE id=?').run(i.quantity,p.id);db.prepare('INSERT INTO stock_movements(product_id,quantity,reason)VALUES(?,?,?)').run(p.id,-i.quantity,`Sale #${s.lastInsertRowid}`)}if(customerId&&total>(+paid||0))db.prepare('UPDATE customers SET balance=balance+? WHERE id=?').run(total-(+paid||0),customerId);return{id:s.lastInsertRowid,total}}))}catch(e){res.status(400).json({error:e.message})}})
app.get('/api/reports/summary',auth,(req,res)=>{const days=Math.min(Math.max(+req.query.days||30,7),365),range=`-${days} days`,sales=rows("SELECT date(created_at)day,COALESCE(SUM(total),0)revenue,COUNT(*)orders FROM sales WHERE created_at>=datetime('now',?) GROUP BY date(created_at) ORDER BY day",[range]),products=rows('SELECT p.name,p.price,p.cost,COALESCE(SUM(si.quantity),0)units,COALESCE(SUM(si.quantity*(si.unit_price-p.cost)),0)profit FROM products p LEFT JOIN sale_items si ON si.product_id=p.id GROUP BY p.id ORDER BY units DESC LIMIT 8'),totals=db.prepare("SELECT COALESCE(SUM(s.total),0)revenue,COALESCE(SUM(si.quantity*(si.unit_price-p.cost)),0)profit,COUNT(DISTINCT s.id)orders FROM sales s LEFT JOIN sale_items si ON si.sale_id=s.id LEFT JOIN products p ON p.id=si.product_id WHERE s.created_at>=datetime('now',?)").get(range);res.json({days,sales,products,totals})})
app.get('/api/forecast',auth,(_q,res)=>res.json(rows("SELECT p.*,COALESCE(SUM(CASE WHEN s.created_at>=datetime('now','-28 days') THEN si.quantity ELSE 0 END),0)sales_28d FROM products p LEFT JOIN sale_items si ON si.product_id=p.id LEFT JOIN sales s ON s.id=si.sale_id GROUP BY p.id").map(p=>{const weekly=Math.max(1,Math.ceil(p.sales_28d/4));return{...p,weeklyDemand:weekly,suggestedOrder:Math.max(0,weekly*2-p.stock),daysCover:Math.floor(p.stock/weekly*7)}})))
app.get('/api/sheet',auth,(req,res)=>{const type=req.query.type||'all',q=`%${req.query.q||''}%`,data=[];if(type==='all'||type==='products')rows('SELECT id,name,sku,category,unit,price,stock,reorder_level,created_at FROM products WHERE name LIKE ? OR sku LIKE ? OR category LIKE ? ORDER BY id DESC',[q,q,q]).forEach(p=>data.push({type:'Product',id:p.id,title:p.name,detail:`${p.sku||'No SKU'} · ${p.category||'Uncategorised'}`,amount:p.price,quantity:p.stock,status:p.stock<=p.reorder_level?'Low stock':'In stock',updated:p.created_at}));if(type==='all'||type==='customers')rows('SELECT id,name,phone,tag,balance,created_at FROM customers WHERE name LIKE ? OR phone LIKE ? OR tag LIKE ? ORDER BY id DESC',[q,q,q]).forEach(c=>data.push({type:'Customer',id:c.id,title:c.name,detail:`${c.phone||'No phone'} · ${c.tag}`,amount:c.balance,quantity:'—',status:c.balance>0?'Credit due':'Settled',updated:c.created_at}));if(type==='all'||type==='sales')rows(`SELECT s.id,s.total,s.paid,s.payment_mode,s.created_at,c.name customer_name,GROUP_CONCAT(p.name||' ×'||si.quantity,', ') items FROM sales s LEFT JOIN customers c ON c.id=s.customer_id LEFT JOIN sale_items si ON si.sale_id=s.id LEFT JOIN products p ON p.id=si.product_id GROUP BY s.id ORDER BY s.id DESC`).filter(s=>(`${s.customer_name||''} ${s.items||''} ${s.payment_mode}`).toLowerCase().includes((req.query.q||'').toLowerCase())).forEach(s=>data.push({type:'Sale',id:s.id,title:`Sale #${String(s.id).padStart(4,'0')}`,detail:`${s.customer_name||'Walk-in'} · ${s.items||'No items'}`,amount:s.total,quantity:'—',status:s.payment_mode,updated:s.created_at}));res.json(data.sort((a,b)=>String(b.updated).localeCompare(String(a.updated))))})
app.post('/api/assistant/parse-sale',auth,(req,res)=>{const t=(req.body.message||'').toLowerCase(),qs=[...t.matchAll(/(\d+)\s*(?:x|kg|bags?|packs?|pieces?|bottles?)?/g)].map(x=>+x[1]),matched=rows('SELECT * FROM products').map(p=>({p,n:p.name.toLowerCase().split(' ').filter(w=>w.length>2&&t.includes(w)).length})).filter(x=>x.n).sort((a,b)=>b.n-a.n),c=rows('SELECT * FROM customers').find(x=>t.includes(x.name.toLowerCase().split(' ')[0])),m=['upi','cash','card','credit'].find(x=>t.includes(x))||'cash';res.json({message:matched.length?'I found a draft sale. Review it before recording.':'Try “sold 2 Ponni Rice to Ravi via UPI”.',draft:{items:matched.slice(0,3).map((x,i)=>({productId:x.p.id,name:x.p.name,price:x.p.price,quantity:qs[i]||1,max:x.p.stock})),customerId:c?.id||null,customerName:c?.name||null,paymentMode:m[0].toUpperCase()+m.slice(1)}})})
app.listen(3001,()=>console.log('API running on http://localhost:3001'))
