import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const api = async (path, options) => { const r = await fetch(`/api${path}`, { headers: {'Content-Type':'application/json'}, ...options }); const d=await r.json(); if(!r.ok) throw new Error(d.error||'Something went wrong'); return d }
const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0)
const date = value => new Date(value + (value?.endsWith('Z')?'':'Z')).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})

function Modal({title, children, close}) { return <div className="overlay"><section className="modal"><button className="x" onClick={close}>×</button><h2>{title}</h2>{children}</section></div> }
function Field({label,...props}) { return <label>{label}<input {...props}/></label> }

function App(){
  const [tab,setTab]=useState('Dashboard'), [data,setData]=useState({}), [products,setProducts]=useState([]), [customers,setCustomers]=useState([]), [sales,setSales]=useState([]), [query,setQuery]=useState(''), [modal,setModal]=useState(null), [toast,setToast]=useState('')
  const refresh=async()=>{const [d,p,c,s]=await Promise.all([api('/dashboard'),api(`/products?q=${query}`),api(`/customers?q=${query}`),api('/sales')]);setData(d);setProducts(p);setCustomers(c);setSales(s)}
  useEffect(()=>{refresh().catch(e=>setToast(e.message))},[query])
  const notify=(msg)=>{setToast(msg);setTimeout(()=>setToast(''),3000)}
  const navigate=t=>{setTab(t);setQuery('')}
  return <main><aside><div className="brand"><span>V</span><div>Vyapaar<small>FLOW</small></div></div><p className="workspace">WORKSPACE</p>{['Dashboard','Sales','Products','Customers','Business'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>navigate(x)}><i>{({Dashboard:'▦',Sales:'↗',Products:'□',Customers:'♙',Business:'⌂'})[x]}</i>{x}</button>)}<div className="side-bottom"><div className="user-avatar">PN</div><div><b>Priya Nair</b><small>Business owner</small></div></div></aside><section className="page"><header><div><p className="eyebrow">{tab==='Dashboard'?'TUESDAY, 23 SEPTEMBER 2026':'OPERATIONS'}</p><h1>{tab==='Dashboard'?'Good morning, Priya':tab}</h1></div><div className="header-actions"><div className="search">⌕<input placeholder="Search records..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{tab==='Sales'&&<button className="primary" onClick={()=>setModal('sale')}>+ New sale</button>}{tab==='Products'&&<button className="primary" onClick={()=>setModal('product')}>+ Add product</button>}{tab==='Customers'&&<button className="primary" onClick={()=>setModal('customer')}>+ Add customer</button>}</div></header>
  {tab==='Dashboard'&&<Dashboard data={data} navigate={navigate} setModal={setModal}/>} {tab==='Products'&&<Products rows={products} setModal={setModal}/>} {tab==='Customers'&&<Customers rows={customers}/>} {tab==='Sales'&&<Sales rows={sales}/>} {tab==='Business'&&<Business notify={notify}/>} 
  {modal==='product'&&<ProductForm close={()=>setModal(null)} done={()=>{setModal(null);refresh();notify('Product added to inventory')}}/>}{modal==='customer'&&<CustomerForm close={()=>setModal(null)} done={()=>{setModal(null);refresh();notify('Customer saved')}}/>}{modal==='sale'&&<SaleForm products={products} customers={customers} close={()=>setModal(null)} done={(id)=>{setModal(null);refresh();notify(`Sale #${id} recorded and stock updated`)}}/>}{modal?.type==='stock'&&<StockForm product={modal.product} close={()=>setModal(null)} done={()=>{setModal(null);refresh();notify('Inventory updated')}}/>}
  {toast&&<div className="toast">✓ {toast}</div>}</section></main>
}
function Dashboard({data,navigate,setModal}){return <><div className="cards"><Metric icon="₹" title="TODAY'S SALES" value={money(data.total)} note={`${data.orders||0} orders today`} color="purple"/><Metric icon="◉" title="OUTSTANDING CREDIT" value={money(data.credit)} note="Across customer ledger" color="orange"/><Metric icon="□" title="PRODUCT CATALOG" value={data.products||0} note="Active products" color="blue"/><Metric icon="!" title="LOW STOCK" value={data.lowStock?.length||0} note="Items need attention" color="red"/></div><div className="dashboard-grid"><section className="panel recent"><div className="panel-title"><div><h2>Recent sales</h2><p>Latest transactions from your counter</p></div><button onClick={()=>navigate('Sales')}>View all →</button></div>{data.recentSales?.length?<table><thead><tr><th>SALE</th><th>CUSTOMER</th><th>PAYMENT</th><th>TOTAL</th></tr></thead><tbody>{data.recentSales.map(s=><tr key={s.id}><td><b>#{String(s.id).padStart(4,'0')}</b><small>{date(s.created_at)}</small></td><td>{s.customer_name||'Walk-in customer'}</td><td><span className={'badge '+s.payment_mode.toLowerCase()}>{s.payment_mode}</span></td><td><b>{money(s.total)}</b></td></tr>)}</tbody></table>:<Empty text="Your sales will appear here."/>}</section><section className="panel low"><div className="panel-title"><div><h2>Stock attention</h2><p>Reorder before you run out</p></div><button onClick={()=>navigate('Products')}>Manage →</button></div>{data.lowStock?.map(p=><div className="stock-row" key={p.id}><div className="product-dot">{p.name[0]}</div><div><b>{p.name}</b><small>{p.sku} · Reorder at {p.reorder_level}</small></div><strong>{p.stock} <small>{p.unit}s</small></strong><button className="icon-btn" onClick={()=>setModal({type:'stock',product:p})}>+</button></div>)||<Empty text="All inventory is healthy."/>}</section></div><section className="panel quick"><div><h2>Quick actions</h2><p>Keep your business moving</p></div><button onClick={()=>setModal('sale')}><i>↗</i>Record a sale</button><button onClick={()=>navigate('Products')}><i>□</i>Manage inventory</button><button onClick={()=>navigate('Customers')}><i>♙</i>Customer ledger</button></section></>}
function Metric({icon,title,value,note,color}){return <section className="metric"><span className={'metric-icon '+color}>{icon}</span><p>{title}</p><h2>{value}</h2><small>{note}</small></section>}
function Products({rows,setModal}){return <section className="panel list"><div className="panel-title"><div><h2>Inventory</h2><p>{rows.length} products matching your search</p></div></div><table><thead><tr><th>PRODUCT</th><th>SKU / CATEGORY</th><th>SELLING PRICE</th><th>STOCK</th><th></th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td><small>{p.sku} · {p.category}</small></td><td>{money(p.price)}</td><td><span className={p.stock<=p.reorder_level?'stock-alert':''}>{p.stock} {p.unit}s</span></td><td><button className="outline" onClick={()=>setModal({type:'stock',product:p})}>Adjust stock</button></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No products found."/>}</section>}
function Customers({rows}){return <section className="panel list"><div className="panel-title"><div><h2>Customer directory</h2><p>Purchase relationships and credit ledger</p></div></div><table><thead><tr><th>CUSTOMER</th><th>PHONE</th><th>TYPE</th><th>OUTSTANDING</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><b>{c.name}</b><small>{c.address}</small></td><td>{c.phone}</td><td><span className="badge regular">{c.tag}</span></td><td className={c.balance?'credit':''}><b>{money(c.balance)}</b></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No customers found."/>}</section>}
function Sales({rows}){return <section className="panel list"><div className="panel-title"><div><h2>Sales history</h2><p>Every transaction, payment, and item</p></div></div><table><thead><tr><th>SALE</th><th>CUSTOMER</th><th>ITEMS</th><th>PAYMENT</th><th>TOTAL</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><b>#{String(s.id).padStart(4,'0')}</b><small>{date(s.created_at)}</small></td><td>{s.customer_name||'Walk-in customer'}</td><td><small>{s.items}</small></td><td><span className={'badge '+s.payment_mode.toLowerCase()}>{s.payment_mode}</span></td><td><b>{money(s.total)}</b><small>Paid {money(s.paid)}</small></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No sales recorded yet."/>}</section>}
function Empty({text}){return <div className="empty">{text}</div>}
function ProductForm({close,done}){const [p,setP]=useState({unit:'piece',stock:0,reorder_level:5});const submit=async e=>{e.preventDefault();await api('/products',{method:'POST',body:JSON.stringify(p)});done()};return <Modal title="Add a product" close={close}><form onSubmit={submit} className="form"><Field label="Product name" required onChange={e=>setP({...p,name:e.target.value})}/><div className="two"><Field label="SKU" onChange={e=>setP({...p,sku:e.target.value})}/><Field label="Category" onChange={e=>setP({...p,category:e.target.value})}/></div><div className="two"><Field label="Cost price" type="number" required onChange={e=>setP({...p,cost:e.target.value})}/><Field label="Selling price" type="number" required onChange={e=>setP({...p,price:e.target.value})}/></div><div className="two"><Field label="Opening stock" type="number" onChange={e=>setP({...p,stock:e.target.value})}/><Field label="Reorder level" type="number" onChange={e=>setP({...p,reorder_level:e.target.value})}/></div><button className="primary wide">Save product</button></form></Modal>}
function CustomerForm({close,done}){const [c,setC]=useState({tag:'Regular'});const submit=async e=>{e.preventDefault();await api('/customers',{method:'POST',body:JSON.stringify(c)});done()};return <Modal title="Add a customer" close={close}><form onSubmit={submit} className="form"><Field label="Full name" required onChange={e=>setC({...c,name:e.target.value})}/><Field label="Phone number" onChange={e=>setC({...c,phone:e.target.value})}/><Field label="Address" onChange={e=>setC({...c,address:e.target.value})}/><label>Customer type<select value={c.tag} onChange={e=>setC({...c,tag:e.target.value})}><option>Regular</option><option>Wholesale</option></select></label><button className="primary wide">Save customer</button></form></Modal>}
function StockForm({product,close,done}){const [quantity,setQuantity]=useState(1),[reason,setReason]=useState('Restock');const submit=async e=>{e.preventDefault();await api(`/products/${product.id}/stock`,{method:'PATCH',body:JSON.stringify({quantity:reason==='Damage'?-quantity:quantity,reason})});done()};return <Modal title={`Adjust ${product.name}`} close={close}><form onSubmit={submit} className="form"><p className="help">Current stock: <b>{product.stock} {product.unit}s</b></p><Field label="Quantity" type="number" min="1" required value={quantity} onChange={e=>setQuantity(+e.target.value)}/><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}><option>Restock</option><option>Damage</option><option>Manual correction</option></select></label><button className="primary wide">Update inventory</button></form></Modal>}
function SaleForm({products,customers,close,done}){const [items,setItems]=useState([]),[customerId,setCustomer]=useState(''),[paymentMode,setMode]=useState('Cash'),[paid,setPaid]=useState('');const total=useMemo(()=>items.reduce((s,i)=>s+i.quantity*i.price,0),[items]);const add=(id)=>{const p=products.find(x=>x.id===+id);if(!p)return;setItems([...items,{productId:p.id,name:p.name,price:p.price,quantity:1,max:p.stock}])};const submit=async e=>{e.preventDefault();const r=await api('/sales',{method:'POST',body:JSON.stringify({customerId:+customerId||null,paymentMode,paid:+paid||0,items})});done(r.id)};return <Modal title="Record a sale" close={close}><form onSubmit={submit} className="form sale-form"><label>Add product<select defaultValue="" onChange={e=>{add(e.target.value);e.target.value=''}}><option value="" disabled>Choose a product</option>{products.map(p=><option key={p.id} value={p.id} disabled={!p.stock}>{p.name} — {p.stock} left</option>)}</select></label><div className="cart">{items.map((x,index)=><div className="cart-row" key={index}><span>{x.name}<small>{money(x.price)} each</small></span><input type="number" min="1" max={x.max} value={x.quantity} onChange={e=>setItems(items.map((a,n)=>n===index?{...a,quantity:+e.target.value}:a))}/><b>{money(x.price*x.quantity)}</b><button type="button" onClick={()=>setItems(items.filter((_,n)=>n!==index))}>×</button></div>)}{!items.length&&<Empty text="Add products to this sale."/>}</div><div className="total">Total <b>{money(total)}</b></div><label>Customer<select value={customerId} onChange={e=>setCustomer(e.target.value)}><option value="">Walk-in customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="two"><label>Payment mode<select value={paymentMode} onChange={e=>setMode(e.target.value)}><option>Cash</option><option>UPI</option><option>Card</option><option>Credit</option></select></label><Field label="Amount paid" type="number" min="0" value={paid} placeholder={total} onChange={e=>setPaid(e.target.value)}/></div><button className="primary wide" disabled={!items.length}>Complete sale · {money(total)}</button></form></Modal>}
function Business({notify}){const [b,setB]=useState(null);useEffect(()=>{api('/business').then(setB)},[]);if(!b)return <Empty text="Loading business profile…"/>;const submit=async e=>{e.preventDefault();await api('/business',{method:'PUT',body:JSON.stringify(b)});notify('Business information updated')};return <section className="panel profile"><div className="panel-title"><div><h2>Business information</h2><p>This appears on your invoices and reports.</p></div></div><form onSubmit={submit} className="form"><Field label="Business name" value={b.name} onChange={e=>setB({...b,name:e.target.value})}/><div className="two"><Field label="Owner" value={b.owner} onChange={e=>setB({...b,owner:e.target.value})}/><Field label="Phone" value={b.phone} onChange={e=>setB({...b,phone:e.target.value})}/></div><div className="two"><Field label="GSTIN" value={b.gstin} onChange={e=>setB({...b,gstin:e.target.value})}/><Field label="Address" value={b.address} onChange={e=>setB({...b,address:e.target.value})}/></div><button className="primary">Save changes</button></form></section>}
createRoot(document.getElementById('root')).render(<App/>)
