import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const api = async (path, options={}) => { const token=localStorage.getItem('vyapaar-token'); const r = await fetch(`/api${path}`, { headers: {'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}, ...options }); const d=await r.json(); if(!r.ok) throw new Error(d.error||'Something went wrong'); return d }
const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0)
const date = value => new Date(value + (value?.endsWith('Z')?'':'Z')).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})

function Modal({title, children, close}) { return <div className="overlay"><section className="modal"><button className="x" onClick={close}>×</button><h2>{title}</h2>{children}</section></div> }
function Field({label,...props}) { return <label>{label}<input {...props}/></label> }

function App(){
  const [session,setSession]=useState(()=>{try{return JSON.parse(localStorage.getItem('vyapaar-user'))}catch{return null}}), [tab,setTab]=useState('Dashboard'), [data,setData]=useState({}), [products,setProducts]=useState([]), [customers,setCustomers]=useState([]), [sales,setSales]=useState([]), [query,setQuery]=useState(''), [modal,setModal]=useState(null), [toast,setToast]=useState('')
  const refresh=async()=>{const [d,p,c,s]=await Promise.all([api('/dashboard'),api(`/products?q=${query}`),api(`/customers?q=${query}`),api('/sales')]);setData(d);setProducts(p);setCustomers(c);setSales(s)}
  useEffect(()=>{if(session)refresh().catch(e=>{setToast(e.message);if(e.message==='Please sign in again')setSession(null)})},[query,session])
  const notify=(msg)=>{setToast(msg);setTimeout(()=>setToast(''),3000)}
  const navigate=t=>{setTab(t);setQuery('')}
  if(!session)return <Login onLogin={setSession}/>
  const isOwner=session.role==='owner'
  return <main><aside><div className="brand"><span>V</span><div>Vyapaar<small>FLOW</small></div></div><p className="workspace">WORKSPACE</p>{['Dashboard','Sales','Products','Customers','Reports','Forecast','Business'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>navigate(x)}><i>{({Dashboard:'▦',Sales:'↗',Products:'□',Customers:'♙',Reports:'▤',Forecast:'⌁',Business:'⌂'})[x]}</i>{x}</button>)}<div className="side-bottom"><div className="user-avatar">{session.name.split(' ').map(x=>x[0]).join('')}</div><div><b>{session.name}</b><small>{session.role}</small></div><button className="signout" onClick={()=>{localStorage.clear();setSession(null)}}>↪</button></div></aside><section className="page"><header><div><p className="eyebrow">{tab==='Dashboard'?'TUESDAY, 23 SEPTEMBER 2026':'OPERATIONS'}</p><h1>{tab==='Dashboard'?`Good morning, ${session.name.split(' ')[0]}`:tab}</h1></div><div className="header-actions"><div className="search">⌕<input placeholder="Search records..." value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="assistant-btn" onClick={()=>setModal('assistant')}>✦ Smart sale</button>{tab==='Sales'&&<button className="primary" onClick={()=>setModal('sale')}>+ New sale</button>}{tab==='Products'&&isOwner&&<button className="primary" onClick={()=>setModal('product')}>+ Add product</button>}{tab==='Customers'&&<button className="primary" onClick={()=>setModal('customer')}>+ Add customer</button>}</div></header>
  {tab==='Dashboard'&&<Dashboard data={data} navigate={navigate} setModal={setModal}/>} {tab==='Products'&&<Products rows={products} setModal={setModal}/>} {tab==='Customers'&&<Customers rows={customers}/>} {tab==='Sales'&&<Sales rows={sales}/>} {tab==='Reports'&&<Reports/>} {tab==='Forecast'&&<Forecast/>} {tab==='Business'&&<Business notify={notify}/>} 
  {modal==='product'&&<ProductForm close={()=>setModal(null)} done={()=>{setModal(null);refresh();notify('Product added to inventory')}}/>}{modal==='customer'&&<CustomerForm close={()=>setModal(null)} done={()=>{setModal(null);refresh();notify('Customer saved')}}/>}{modal==='sale'&&<SaleForm products={products} customers={customers} close={()=>setModal(null)} done={(id)=>{setModal(null);refresh();notify(`Sale #${id} recorded and stock updated`)}}/>}{modal==='assistant'&&<Assistant products={products} customers={customers} close={()=>setModal(null)} done={(id)=>{setModal(null);refresh();notify(`Smart sale #${id} recorded`)}}/>}{modal?.type==='stock'&&<StockForm product={modal.product} close={()=>setModal(null)} done={()=>{setModal(null);refresh();notify('Inventory updated')}}/>}
  {toast&&<div className="toast">✓ {toast}</div>}</section></main>
}
function Dashboard({data,navigate,setModal}){return <><div className="cards"><Metric icon="₹" title="TODAY'S SALES" value={money(data.total)} note={`${data.orders||0} orders today`} color="purple"/><Metric icon="◉" title="OUTSTANDING CREDIT" value={money(data.credit)} note="Across customer ledger" color="orange"/><Metric icon="□" title="PRODUCT CATALOG" value={data.products||0} note="Active products" color="blue"/><Metric icon="!" title="LOW STOCK" value={data.lowStock?.length||0} note="Items need attention" color="red"/></div><div className="dashboard-grid"><section className="panel recent"><div className="panel-title"><div><h2>Recent sales</h2><p>Latest transactions from your counter</p></div><button onClick={()=>navigate('Sales')}>View all →</button></div>{data.recentSales?.length?<table><thead><tr><th>SALE</th><th>CUSTOMER</th><th>PAYMENT</th><th>TOTAL</th></tr></thead><tbody>{data.recentSales.map(s=><tr key={s.id}><td><b>#{String(s.id).padStart(4,'0')}</b><small>{date(s.created_at)}</small></td><td>{s.customer_name||'Walk-in customer'}</td><td><span className={'badge '+s.payment_mode.toLowerCase()}>{s.payment_mode}</span></td><td><b>{money(s.total)}</b></td></tr>)}</tbody></table>:<Empty text="Your sales will appear here."/>}</section><section className="panel low"><div className="panel-title"><div><h2>Stock attention</h2><p>Reorder before you run out</p></div><button onClick={()=>navigate('Products')}>Manage →</button></div>{data.lowStock?.map(p=><div className="stock-row" key={p.id}><div className="product-dot">{p.name[0]}</div><div><b>{p.name}</b><small>{p.sku} · Reorder at {p.reorder_level}</small></div><strong>{p.stock} <small>{p.unit}s</small></strong><button className="icon-btn" onClick={()=>setModal({type:'stock',product:p})}>+</button></div>)||<Empty text="All inventory is healthy."/>}</section></div><section className="panel quick"><div><h2>Quick actions</h2><p>Keep your business moving</p></div><button onClick={()=>setModal('sale')}><i>↗</i>Record a sale</button><button onClick={()=>navigate('Products')}><i>□</i>Manage inventory</button><button onClick={()=>navigate('Customers')}><i>♙</i>Customer ledger</button></section></>}
function Metric({icon,title,value,note,color}){return <section className="metric"><span className={'metric-icon '+color}>{icon}</span><p>{title}</p><h2>{value}</h2><small>{note}</small></section>}
function Products({rows,setModal}){return <section className="panel list"><div className="panel-title"><div><h2>Inventory</h2><p>{rows.length} products matching your search</p></div></div><table><thead><tr><th>PRODUCT</th><th>SKU / CATEGORY</th><th>SELLING PRICE</th><th>STOCK</th><th></th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td><small>{p.sku} · {p.category}</small></td><td>{money(p.price)}</td><td><span className={p.stock<=p.reorder_level?'stock-alert':''}>{p.stock} {p.unit}s</span></td><td><button className="outline" onClick={()=>setModal({type:'stock',product:p})}>Adjust stock</button></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No products found."/>}</section>}
function Customers({rows}){return <section className="panel list"><div className="panel-title"><div><h2>Customer directory</h2><p>Purchase relationships and credit ledger</p></div></div><table><thead><tr><th>CUSTOMER</th><th>PHONE</th><th>TYPE</th><th>OUTSTANDING</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><b>{c.name}</b><small>{c.address}</small></td><td>{c.phone}</td><td><span className="badge regular">{c.tag}</span></td><td className={c.balance?'credit':''}><b>{money(c.balance)}</b></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No customers found."/>}</section>}
function Sales({rows}){return <section className="panel list"><div className="panel-title"><div><h2>Sales history</h2><p>Every transaction, payment, and item</p></div></div><table><thead><tr><th>SALE</th><th>CUSTOMER</th><th>ITEMS</th><th>PAYMENT</th><th>TOTAL</th><th></th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><b>#{String(s.id).padStart(4,'0')}</b><small>{date(s.created_at)}</small></td><td>{s.customer_name||'Walk-in customer'}</td><td><small>{s.items}</small></td><td><span className={'badge '+s.payment_mode.toLowerCase()}>{s.payment_mode}</span></td><td><b>{money(s.total)}</b><small>Paid {money(s.paid)}</small></td><td><button className="outline" onClick={()=>printInvoice(s.id)}>Invoice</button></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No sales recorded yet."/>}</section>}
function Empty({text}){return <div className="empty">{text}</div>}
function ProductForm({close,done}){const [p,setP]=useState({unit:'piece',stock:0,reorder_level:5});const submit=async e=>{e.preventDefault();await api('/products',{method:'POST',body:JSON.stringify(p)});done()};return <Modal title="Add a product" close={close}><form onSubmit={submit} className="form"><Field label="Product name" required onChange={e=>setP({...p,name:e.target.value})}/><div className="two"><Field label="SKU" onChange={e=>setP({...p,sku:e.target.value})}/><Field label="Category" onChange={e=>setP({...p,category:e.target.value})}/></div><div className="two"><Field label="Cost price" type="number" required onChange={e=>setP({...p,cost:e.target.value})}/><Field label="Selling price" type="number" required onChange={e=>setP({...p,price:e.target.value})}/></div><div className="two"><Field label="Opening stock" type="number" onChange={e=>setP({...p,stock:e.target.value})}/><Field label="Reorder level" type="number" onChange={e=>setP({...p,reorder_level:e.target.value})}/></div><button className="primary wide">Save product</button></form></Modal>}
function CustomerForm({close,done}){const [c,setC]=useState({tag:'Regular'});const submit=async e=>{e.preventDefault();await api('/customers',{method:'POST',body:JSON.stringify(c)});done()};return <Modal title="Add a customer" close={close}><form onSubmit={submit} className="form"><Field label="Full name" required onChange={e=>setC({...c,name:e.target.value})}/><Field label="Phone number" onChange={e=>setC({...c,phone:e.target.value})}/><Field label="Address" onChange={e=>setC({...c,address:e.target.value})}/><label>Customer type<select value={c.tag} onChange={e=>setC({...c,tag:e.target.value})}><option>Regular</option><option>Wholesale</option></select></label><button className="primary wide">Save customer</button></form></Modal>}
function StockForm({product,close,done}){const [quantity,setQuantity]=useState(1),[reason,setReason]=useState('Restock');const submit=async e=>{e.preventDefault();await api(`/products/${product.id}/stock`,{method:'PATCH',body:JSON.stringify({quantity:reason==='Damage'?-quantity:quantity,reason})});done()};return <Modal title={`Adjust ${product.name}`} close={close}><form onSubmit={submit} className="form"><p className="help">Current stock: <b>{product.stock} {product.unit}s</b></p><Field label="Quantity" type="number" min="1" required value={quantity} onChange={e=>setQuantity(+e.target.value)}/><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}><option>Restock</option><option>Damage</option><option>Manual correction</option></select></label><button className="primary wide">Update inventory</button></form></Modal>}
function SaleForm({products,customers,close,done}){const [items,setItems]=useState([]),[customerId,setCustomer]=useState(''),[paymentMode,setMode]=useState('Cash'),[paid,setPaid]=useState('');const total=useMemo(()=>items.reduce((s,i)=>s+i.quantity*i.price,0),[items]);const add=(id)=>{const p=products.find(x=>x.id===+id);if(!p)return;setItems([...items,{productId:p.id,name:p.name,price:p.price,quantity:1,max:p.stock}])};const submit=async e=>{e.preventDefault();const r=await api('/sales',{method:'POST',body:JSON.stringify({customerId:+customerId||null,paymentMode,paid:+paid||0,items})});done(r.id)};return <Modal title="Record a sale" close={close}><form onSubmit={submit} className="form sale-form"><label>Add product<select defaultValue="" onChange={e=>{add(e.target.value);e.target.value=''}}><option value="" disabled>Choose a product</option>{products.map(p=><option key={p.id} value={p.id} disabled={!p.stock}>{p.name} — {p.stock} left</option>)}</select></label><div className="cart">{items.map((x,index)=><div className="cart-row" key={index}><span>{x.name}<small>{money(x.price)} each</small></span><input type="number" min="1" max={x.max} value={x.quantity} onChange={e=>setItems(items.map((a,n)=>n===index?{...a,quantity:+e.target.value}:a))}/><b>{money(x.price*x.quantity)}</b><button type="button" onClick={()=>setItems(items.filter((_,n)=>n!==index))}>×</button></div>)}{!items.length&&<Empty text="Add products to this sale."/>}</div><div className="total">Total <b>{money(total)}</b></div><label>Customer<select value={customerId} onChange={e=>setCustomer(e.target.value)}><option value="">Walk-in customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="two"><label>Payment mode<select value={paymentMode} onChange={e=>setMode(e.target.value)}><option>Cash</option><option>UPI</option><option>Card</option><option>Credit</option></select></label><Field label="Amount paid" type="number" min="0" value={paid} placeholder={total} onChange={e=>setPaid(e.target.value)}/></div><button className="primary wide" disabled={!items.length}>Complete sale · {money(total)}</button></form></Modal>}
function Business({notify}){const [b,setB]=useState(null);useEffect(()=>{api('/business').then(setB)},[]);if(!b)return <Empty text="Loading business profile…"/>;const submit=async e=>{e.preventDefault();await api('/business',{method:'PUT',body:JSON.stringify(b)});notify('Business information updated')};return <section className="panel profile"><div className="panel-title"><div><h2>Business information</h2><p>This appears on your invoices and reports.</p></div></div><form onSubmit={submit} className="form"><Field label="Business name" value={b.name} onChange={e=>setB({...b,name:e.target.value})}/><div className="two"><Field label="Owner" value={b.owner} onChange={e=>setB({...b,owner:e.target.value})}/><Field label="Phone" value={b.phone} onChange={e=>setB({...b,phone:e.target.value})}/></div><div className="two"><Field label="GSTIN" value={b.gstin} onChange={e=>setB({...b,gstin:e.target.value})}/><Field label="Address" value={b.address} onChange={e=>setB({...b,address:e.target.value})}/></div><button className="primary">Save changes</button></form></section>}

const printInvoice = async id => {
  try {
    const s = await api(`/sales/${id}`)
    const win = window.open('','_blank')
    win.document.write(`<html><head><title>Invoice #${s.id}</title><style>body{font-family:sans-serif;padding:2rem;max-width:800px;margin:0 auto} table{width:100%;border-collapse:collapse;margin:2rem 0} th,td{padding:0.5rem;text-align:left;border-bottom:1px solid #ddd} .right{text-align:right} .total{font-size:1.5em;font-weight:bold}</style></head><body><h1>INVOICE</h1><p><b>${s.business_name}</b><br>${s.address}<br>Phone: ${s.business_phone}<br>GSTIN: ${s.gstin}</p><hr><p><b>Invoice No:</b> ${s.id}<br><b>Date:</b> ${new Date(s.created_at).toLocaleString('en-IN')}<br><b>Customer:</b> ${s.customer_name||'Walk-in'}</p><table><thead><tr><th>Item</th><th>Qty</th><th class="right">Price</th><th class="right">Amount</th></tr></thead><tbody>${s.items.map(i=>`<tr><td>${i.name}</td><td>${i.quantity}</td><td class="right">${money(i.unit_price)}</td><td class="right">${money(i.quantity*i.unit_price)}</td></tr>`).join('')}</tbody></table><div class="right total">Total: ${money(s.total)}</div><div class="right">Payment Mode: ${s.payment_mode}</div><script>window.print()</script></body></html>`)
    win.document.close()
  } catch (err) {
    alert(err.message)
  }
}

function Login({onLogin}){
  const [email,setEmail]=useState('owner@annapoorna.test'), [password,setPassword]=useState('owner123'), [error,setError]=useState('')
  const submit = async e => {
    e.preventDefault()
    try {
      const res = await api('/auth/login', { method: 'POST', body: JSON.stringify({email, password}) })
      localStorage.setItem('vyapaar-token', res.token)
      localStorage.setItem('vyapaar-user', JSON.stringify(res.user))
      onLogin(res.user)
    } catch (err) {
      setError(err.message)
    }
  }
  return <div className="overlay"><section className="modal"><div className="brand"><span>V</span><div>Vyapaar<small>FLOW</small></div></div><h2>Sign in</h2>{error && <div style={{color:'var(--red)'}}>{error}</div>}<form onSubmit={submit} className="form"><Field label="Email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><Field label="Password" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary wide">Sign in</button></form></section></div>
}

function Reports(){
  const [data,setData]=useState(null),[days,setDays]=useState(30)
  useEffect(()=>{api(`/reports/summary?days=${days}`).then(setData)},[days])
  if(!data)return <Empty text="Loading reports..."/>
  return <section className="panel"><div className="panel-title"><div><h2>Business Reports</h2><p>Revenue and product performance</p></div><select value={days} onChange={e=>setDays(+e.target.value)}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></div><div className="cards"><Metric icon="₹" title="TOTAL REVENUE" value={money(data.totals.revenue)} color="green"/><Metric icon="↗" title="EST. PROFIT" value={money(data.totals.profit)} color="purple"/><Metric icon="□" title="ORDERS" value={data.totals.orders} color="blue"/></div><h3>Top Products</h3><table><thead><tr><th>PRODUCT</th><th>UNITS SOLD</th><th>REVENUE</th><th>PROFIT</th></tr></thead><tbody>{data.products.map(p=><tr key={p.name}><td><b>{p.name}</b></td><td>{p.units}</td><td>{money(p.units*p.price)}</td><td className="green">+{money(p.profit)}</td></tr>)}</tbody></table></section>
}

function Forecast(){
  const [rows,setRows]=useState([])
  useEffect(()=>{api('/forecast').then(setRows)},[])
  return <section className="panel"><div className="panel-title"><div><h2>Inventory Forecast</h2><p>AI-driven restocking suggestions based on past 28 days</p></div></div><table><thead><tr><th>PRODUCT</th><th>CURRENT STOCK</th><th>WEEKLY DEMAND</th><th>DAYS COVER</th><th>SUGGESTED ORDER</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{p.stock}</td><td>{p.weeklyDemand}/wk</td><td><span className={p.daysCover<7?'stock-alert':''}>{p.daysCover} days</span></td><td>{p.suggestedOrder>0?<b>Order {p.suggestedOrder}</b>:<span className="badge regular">Optimal</span>}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="Not enough data for forecasting."/>}</section>
}

function Assistant({close,done,products,customers}){
  const [msg,setMsg]=useState(''), [res,setRes]=useState(null), [loading,setLoading]=useState(false)
  const submit = async e => {
    e.preventDefault(); setLoading(true)
    try { setRes(await api('/assistant/parse-sale', {method:'POST',body:JSON.stringify({message:msg})})) }
    catch(err){ alert(err.message) }
    finally { setLoading(false) }
  }
  const confirm = async () => {
    if(!res?.draft) return
    const r = await api('/sales', {method:'POST', body:JSON.stringify({customerId:res.draft.customerId, paymentMode:res.draft.paymentMode, paid:res.draft.items.reduce((sum,i)=>sum+i.price*i.quantity,0), items:res.draft.items})})
    done(r.id)
  }
  return <Modal title="Smart Sale Assistant" close={close}><div className="assistant"><p className="help">Type a natural language command like "sold 2 ponni rice and 1 tata salt to ravi via upi"</p><form onSubmit={submit} className="form" style={{display:'flex',gap:10}}><input style={{flex:1}} autoFocus placeholder="Message..." value={msg} onChange={e=>setMsg(e.target.value)}/><button className="primary" disabled={loading||!msg.trim()}>Analyze</button></form>{res&&<div className="assistant-response"><p>{res.message}</p>{res.draft?.items?.length>0&&<div className="draft-sale"><div className="cart">{res.draft.items.map((x,i)=><div className="cart-row" key={i}><span>{x.name}</span><b>{x.quantity} × {money(x.price)}</b></div>)}</div><div className="two"><div className="badge regular">{res.draft.customerName||'Walk-in'}</div><div className="badge green">{res.draft.paymentMode}</div></div><button className="primary wide" style={{marginTop:15}} onClick={confirm}>Confirm & Record Sale</button></div>}</div>}</div></Modal>
}

createRoot(document.getElementById('root')).render(<App/>)
